/// FILE: pubspec.yaml

name: maitri_frontend
description: A Flutter application with voice, charts, animations, and real-time features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  # Authentication & Security
  crypto: ^3.0.3
  
  # Permissions
  permission_handler: ^11.0.1

  # Camera
  camera: ^0.10.5
  
  # ML Kit
  google_mlkit_face_detection: ^0.9.0
  
  # Video
  video_player: ^2.8.2
  
  # State management
  flutter_riverpod: ^2.4.0
  
  # Routing
  go_router: ^12.0.0
  
  # Charts and data visualization
  fl_chart: ^0.65.0
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Animations
  lottie: ^2.7.0
  # rive: ^0.12.0  # Alternative animation option
  
  # Speech and TTS
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  
  # Networking
  http: ^1.1.2
  
  # WebSocket support
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/videos/
    - assets/images/background/

# Platform-specific notes:
# - Web: speech_to_text has limited browser support, test thoroughly
# - Web: WebSockets work natively but check CORS policies
# - iOS: Requires NSMicrophoneUsageDescription and NSSpeechRecognitionUsageDescription in Info.plist
# - Android: Requires RECORD_AUDIO and INTERNET permissions in AndroidManifest.xml